module7-task2
htmlacademy-php/1293483-readme-12 pull request #13
Opened 2020-05-20 13:41 UTC by Seetochka

2020-05-20 13:48 UTC, pyatnitsev commented on add.php
а это работает без session_start() ?

2020-05-20 13:48 UTC, pyatnitsev commented on logout.php
> +$_SESSION = [];
а почему не session_destroy() ?

2020-05-20 14:00 UTC, Seetochka commented on add.php
Я написала его один раз в init, чтобы не писать в каждом сценарии

2020-05-20 15:28 UTC, pyatnitsev commented on add.php
Ок, нет вопросов :)

2020-05-22 19:08 UTC, pyatnitsev commented on index.php
> +        header('Location: feed.php');
Добавь die();

2020-05-22 19:17 UTC, pyatnitsev requested changes

2020-05-22 19:17 UTC, pyatnitsev commented on logout.php
> +header("Location: /");
die();

2020-05-23 12:23 UTC, pyatnitsev approved these changes

2020-05-23 12:23 UTC, merged