module8-task2
htmlacademy-php/1293483-readme-12 pull request #15
Opened 2020-06-05 13:45 UTC by Seetochka

2020-06-08 20:24 UTC, pyatnitsev requested changes
Поправь вещи в запросах, 
вроде count вместо взятия массива, и зведочку в запросе. 

высчитывания likes можно попробовать сделать в SQL, но если сложно - не стоит тратить на это время. 

В целом - хороший код.

2020-06-08 20:24 UTC, pyatnitsev commented on actions/repost.php
> +if (empty($post)) {
Работать будет, но по-хорошему для таких переходов нужно проверять что не изменился домен, что бы не отправить пользователя наружу (потенциальная уязвимость)

2020-06-08 20:24 UTC, pyatnitsev commented on actions/repost.php
> +switch ($content_type) {
тут можно немножко объединить: 
case 'photo'
case 'video'
case 'link':
$repost[$content_type] = $post[$content_type];
break;
case 'quote':
//

2020-06-08 20:24 UTC, pyatnitsev commented on pages/adding-post.html
> +    <link rel="stylesheet" href="../css/main.css">
Абсолютные URL /css/main.css предпочтительнее, но ок, менять не стоит.

2020-06-08 20:24 UTC, pyatnitsev commented on popular.php
> +
а нельзя это прямо в SQL-запросе посчитать, или сложно?

2020-06-08 20:24 UTC, pyatnitsev commented on post.php
> +
а если не result? то может быть стоит показать ошибку пользователю?

2020-06-08 20:24 UTC, pyatnitsev commented on sql-queries.php
> +function is_reposted($connection, int $post_id, int $user_id): bool {
Достаточно взять count, быстрее будет.

2020-06-08 20:24 UTC, pyatnitsev commented on sql-queries.php
> +    $sql_subscription = 'SELECT * FROM subscriptions WHERE follower_id = ? AND author_id = ?';
Звездочки в запросе не хорошо :(

2020-06-08 20:24 UTC, pyatnitsev commented on actions/repost.php
> +if (empty($post)) {
Исправлять не требуется, просто как информация

2020-06-09 08:53 UTC, Seetochka commented on sql-queries.php
> +function is_reposted($connection, int $post_id, int $user_id): bool {
Не поняла, я же здесь проверяю есть ли определенная запись в БД, как это сделать через count?

2020-06-09 09:11 UTC, pyatnitsev commented on sql-queries.php
> +function is_reposted($connection, int $post_id, int $user_id): bool {
Ок, если там одна запись - не принципиально. 
А так - можно обернуть SELECT count(p.id) ...
и возвращать результат больше > 0

2020-06-14 08:04 UTC, pyatnitsev commented on sql-queries.php
> +    $user_data_id = $_SESSION['user']['id'];
это же тоже часть params - лучше такое передать снаружи функции.

2020-06-14 08:55 UTC, pyatnitsev approved these changes

2020-06-14 08:55 UTC, merged